### ISSUE TITLE
ошибка при запуске

### ISSUE THREAD

**Issue by sanglyb** [altlinux/gpupdate#31]
При запуске выскакивает следующая ошибка
Apply group policies for computer.
Traceback (most recent call last):
  File "/usr/sbin/gpoa", line 131, in <module>
    main()
  File "/usr/sbin/gpoa", line 128, in main
    controller.run()
  File "/usr/sbin/gpoa", line 90, in run
    self.start_backend()
  File "/usr/sbin/gpoa", line 106, in start_backend
    back.retrieve_and_store()
  File "/usr/lib/python3/site-packages/gpoa/backend/samba_backend.py", line 71, in retrieve_and_store
    gptobj.merge()
  File "/usr/lib/python3/site-packages/gpoa/gpt/gpt.py", line 183, in merge
    util.preg.merge_polfile(self._user_regpol, self.machine_sid)
AttributeError: 'gpt' object has no attribute 'machine_sid'

**Comment by NIR-Ginko** [comment]
Oh, what a nice bug you've triggered. Will fix ASAP.

**Comment by NIR-Ginko** [comment]
@sanglyb , you may try to test fix https://github.com/altlinux/gpupdate/pull/32 . It will take some time to test it by ourselves but I can ensure you it won't be left "as is".
